# Generated by Django 4.1.4 on 2023-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(help_text='Name for internal refernce, limit is upto 50 characters.', max_length=50)),
                ('client_description', models.TextField(help_text='Description limit is upto 1000 characters. Add name address etc as to be shown on invoice', max_length=1000, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('full_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
