# Generated by Django 4.1.4 on 2022-12-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_leads_address_alter_leads_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='address',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='linkedin',
        ),
    ]
