# Generated by Django 4.1.4 on 2022-12-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_leads_address_remove_leads_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='company_name',
            field=models.IntegerField(default=0),
        ),
    ]
