# Generated by Django 4.1.4 on 2022-12-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_leads_address_leads_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='address',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='company_name',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='company_website',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Company Website'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='contact_name',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='contact_number',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='job_title',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Job Tittle'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='jobs',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Jobs'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='linkedin',
            field=models.CharField(default='n/a', max_length=200, verbose_name='Linkedin'),
        ),
    ]
