# Generated by Django 4.1.4 on 2022-12-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_leads_address_alter_leads_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='email',
            new_name='emails',
        ),
    ]
